name: experimental
on: workflow_dispatch
jobs:
  expt-job-a:
    runs-on: ubuntu-latest
    steps:
      - name: do we have gh cli?
        run: which gh
      - name: do we have yq?
        run: which yq
