name: experimental
on: workflow_dispatch
jobs:
  expt-job-a:
    runs-on: ubuntu-latest
    steps:
      - name: do we have gh cli?
        run: which gh
      - name: do we have yq?
        run: which yq || echo "no yq"
      - name: show path
        run: |
          echo $PATH
          for path in ${PATH//:/ }; do
            echo "$path"
            echo '---------------------------------------------'
            ls $path || /bin/true
            echo '============================================='
          done
